package vn.vht.qtkhcn.hoso.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import jakarta.persistence.EntityNotFoundException;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import vn.vht.qtkhcn.hoso.domain.HoiDongCap;
import vn.vht.qtkhcn.hoso.domain.HoiDongXetDuyet;
import vn.vht.qtkhcn.hoso.repository.HoiDongXetDuyetRepository;

class HoiDongQueryServiceTest {

    private HoiDongXetDuyetRepository repository;
    private HoiDongQueryService service;

    @BeforeEach void setUp() {
        repository = mock(HoiDongXetDuyetRepository.class);
        service = new HoiDongQueryService(repository);
    }

    @Test void listsAllCouncilsRegardlessOfOrigin() {
        HoiDongXetDuyet manual = council(1L, "HS-1", HoiDongCap.CO_SO, null);
        HoiDongXetDuyet autoGenerated = council(2L, "HS-2", HoiDongCap.TAP_DOAN, "T18B");
        when(repository.findAll()).thenReturn(List.of(manual, autoGenerated));

        var result = service.findAll();

        assertEquals(2, result.size());
        assertEquals("HS-1", result.get(0).hoSoId());
        assertEquals(null, result.get(0).sourceTaskDefinitionKey());
        assertEquals("T18B", result.get(1).sourceTaskDefinitionKey());
    }

    @Test void findByIdReturnsBodyWithVersionForOptimisticLocking() {
        HoiDongXetDuyet entity = council(5L, "HS-1", HoiDongCap.CO_SO, null);
        entity.setVersion(3L);
        when(repository.findById(5L)).thenReturn(Optional.of(entity));

        VersionedResponse<vn.vht.qtkhcn.hoso.web.dto.HoiDongXetDuyetResponse> result = service.findById(5L);

        assertEquals(3L, result.version());
        assertEquals(5L, result.body().id());
    }

    @Test void findByIdThrowsWhenMissing() {
        when(repository.findById(9L)).thenReturn(Optional.empty());

        assertThrows(EntityNotFoundException.class, () -> service.findById(9L));
    }

    private static HoiDongXetDuyet council(long id, String hoSoId, HoiDongCap cap, String sourceTaskDefinitionKey) {
        HoiDongXetDuyet entity = new HoiDongXetDuyet();
        entity.setId(id);
        entity.setMaHoiDong("HD-" + id);
        entity.setHoSoId(hoSoId);
        entity.setCap(cap);
        entity.setSourceTaskDefinitionKey(sourceTaskDefinitionKey);
        return entity;
    }
}
