package vn.vht.qtkhcn.identity.web;
import static vn.vht.qtkhcn.identity.web.dto.IdentityDtos.*; import jakarta.validation.Valid; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import vn.vht.qtkhcn.identity.service.IdentityService;
@RestController @RequestMapping("/api") public class IdentityController { private final IdentityService s; public IdentityController(IdentityService s){this.s=s;}
 @GetMapping("/organizations") List<OrganizationResponse> organizations(){return s.organizations();} @PostMapping("/organizations") @ResponseStatus(HttpStatus.CREATED) OrganizationResponse create(@Valid @RequestBody OrganizationRequest x){return s.createOrganization(x);}@PutMapping("/organizations/{id}") OrganizationResponse update(@PathVariable UUID id,@Valid @RequestBody OrganizationRequest x){return s.updateOrganization(id,x);}@DeleteMapping("/organizations/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteOrg(@PathVariable UUID id){s.deleteOrganization(id);}
 @GetMapping("/permissions") List<PermissionResponse> permissions(){return s.permissions();}@PostMapping("/permissions") @ResponseStatus(HttpStatus.CREATED) PermissionResponse create(@Valid @RequestBody PermissionRequest x){return s.createPermission(x);}@PutMapping("/permissions/{id}") PermissionResponse update(@PathVariable UUID id,@Valid @RequestBody PermissionRequest x){return s.updatePermission(id,x);}@DeleteMapping("/permissions/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deletePermission(@PathVariable UUID id){s.deletePermission(id);}
 @GetMapping("/features") List<FeatureResponse> features(){return s.features();}
 @GetMapping("/roles") List<RoleResponse> roles(){return s.roles();}@PostMapping("/roles") @ResponseStatus(HttpStatus.CREATED) RoleResponse create(@Valid @RequestBody RoleRequest x){return s.createRole(x);}@PutMapping("/roles/{id}") RoleResponse update(@PathVariable UUID id,@Valid @RequestBody RoleRequest x){return s.updateRole(id,x);}@DeleteMapping("/roles/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteRole(@PathVariable UUID id){s.deleteRole(id);}
 @GetMapping("/users") List<UserResponse> users(){return s.users();}@PostMapping("/users") @ResponseStatus(HttpStatus.CREATED) UserResponse create(@Valid @RequestBody UserRequest x){return s.createUser(x);}@PutMapping("/users/{id}") UserResponse update(@PathVariable UUID id,@Valid @RequestBody UserRequest x){return s.updateUser(id,x);}@DeleteMapping("/users/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteUser(@PathVariable UUID id){s.deleteUser(id);}
 @GetMapping("/data-scopes") List<DataScopeResponse> dataScopes(){return s.dataScopes();}
 @GetMapping("/users/{id}/role-assignments") List<AssignmentResponse> assignments(@PathVariable UUID id){return s.assignments(id);}@PostMapping("/users/{id}/role-assignments") @ResponseStatus(HttpStatus.CREATED) AssignmentResponse assign(@PathVariable UUID id,@Valid @RequestBody AssignmentRequest x){return s.assign(id,x);}@DeleteMapping("/users/{id}/role-assignments/{assignmentId}") @ResponseStatus(HttpStatus.NO_CONTENT) void revoke(@PathVariable UUID id,@PathVariable UUID assignmentId){s.revoke(id,assignmentId);}
 @GetMapping("/apps") List<AppResponse> apps(){return s.apps();}@GetMapping("/users/{id}/apps") UserAppsResponse userApps(@PathVariable UUID id){return s.userApps(id);}@PutMapping("/users/{id}/apps") UserAppsResponse replaceUserApps(@PathVariable UUID id,@Valid @RequestBody UserAppsRequest x){return s.replaceUserApps(id,x.appCodes());}
 @GetMapping("/audit-log") List<AuditLogResponse> auditLog(){return s.auditLog();}
 // Bản public (chặn bằng DevApiKeyFilter) song song với /internal/users/{identity}/effective-permissions
 // (chặn bằng InternalServiceTokenFilter) — để Angular gọi được từ trình duyệt mà không lộ service-token.
 @GetMapping("/effective-permissions/{identity}") EffectivePermissionsResponse effectivePermissions(@PathVariable String identity){return s.effective(identity);}
}
