// BM.02.00/CV — Công văn đăng ký xét duyệt nhiệm vụ KHCN.
// Nguồn: outputs/BM.02.00.CV-DKI-Xet_duyet.NV.form.json (export Camunda Form Designer 8.9.0).
// Có 2 chế độ (toggle `cheDoXemVanBan`): (1) soạn thảo — nhập liệu từng trường trong nhóm
// `Group_soan_thao`; (2) xem văn bản hoàn chỉnh — khối `html` ghép công văn theo đúng thể thức,
// nội suy `{{key}}` từ dữ liệu đã nhập (FormRenderer đã hỗ trợ `group`/`html`/`defaultValue`).
export const congVanDangKyXetDuyetNvKhcnSchema = {
  executionPlatform: 'Camunda Cloud',
  executionPlatformVersion: '8.9.0',
  schemaVersion: 19,
  type: 'default',
  id: 'bm-02-00-cv-dang-ky-xet-duyet-nv-khcn',
  components: [
    {
      type: 'html',
      id: 'Html_huong_dan_che_do',
      content:
        '<div style="padding:10px 12px;background:#f4f7fb;border-left:4px solid #0f62fe"><strong>Cách sử dụng:</strong> Nhập dữ liệu bên dưới, sau đó bật <em>Xem văn bản hoàn chỉnh</em>. Các ô nhập sẽ được ẩn và dữ liệu được ghép vào đúng thể thức công văn.</div>',
    },
    {
      type: 'checkbox',
      id: 'Field_che_do_xem_van_ban',
      key: 'cheDoXemVanBan',
      label: 'Xem văn bản hoàn chỉnh',
      description: 'Bỏ chọn để quay lại chỉnh sửa dữ liệu.',
      defaultValue: false,
    },
    {
      type: 'group',
      id: 'Group_soan_thao',
      label: 'Thông tin soạn thảo',
      conditional: { hide: '=cheDoXemVanBan = true' },
      components: [
        {
          type: 'html',
          id: 'Html_thong_tin_van_ban',
          content:
            '<div style="margin:14px 0 4px;padding:8px 10px;background:#eef3f8;border-left:4px solid #1f5a94;font-weight:700">1. Thông tin văn bản</div>',
        },
        {
          type: 'textfield',
          id: 'Field_don_vi_cap_tren',
          key: 'donViCapTren',
          label: 'Đơn vị cấp trên',
          defaultValue: 'TẬP ĐOÀN CÔNG NGHIỆP - VIỄN THÔNG QUÂN ĐỘI',
        },
        {
          type: 'textfield',
          id: 'Field_don_vi_ban_hanh',
          key: 'donViBanHanh',
          label: 'Đơn vị ban hành',
          validate: { required: true },
          defaultValue: 'TCT CÔNG NGHIỆP CÔNG NGHỆ CAO VIETTEL',
        },
        {
          type: 'textfield',
          id: 'Field_so_cong_van',
          key: 'soCongVan',
          label: 'Số công văn',
          validate: { required: true },
        },
        {
          type: 'textfield',
          id: 'Field_ky_hieu',
          key: 'kyHieuCongVan',
          label: 'Ký hiệu',
          validate: { required: true },
          defaultValue: 'VHT-K1',
        },
        {
          type: 'textfield',
          id: 'Field_trich_yeu',
          key: 'trichYeu',
          label: 'Trích yếu',
          validate: { required: true },
          defaultValue: 'V/v xin ý kiến thẩm định Hồ sơ đăng ký xét duyệt NV KHCN',
        },
        {
          type: 'textfield',
          id: 'Field_dia_danh',
          key: 'diaDanh',
          label: 'Địa danh',
          validate: { required: true },
          defaultValue: 'Hà Nội',
        },
        {
          type: 'textfield',
          id: 'Field_ngay',
          key: 'ngayVanBan',
          label: 'Ngày',
          validate: { required: true },
        },
        {
          type: 'textfield',
          id: 'Field_thang',
          key: 'thangVanBan',
          label: 'Tháng',
          validate: { required: true },
        },
        {
          type: 'textfield',
          id: 'Field_nam',
          key: 'namKy',
          label: 'Năm ký',
          validate: { required: true },
          defaultValue: '2026',
        },
        {
          type: 'textarea',
          id: 'Field_kinh_gui',
          key: 'kinhGui',
          label: 'Kính gửi',
          validate: { required: true },
          defaultValue: '- Ban Tổng Giám đốc Tập đoàn;\n- Cơ quan Quản lý KHCN Tập đoàn.',
          description: 'Mỗi cơ quan nhận trình bày trên một dòng.',
        },
        {
          type: 'html',
          id: 'Html_noi_dung',
          content:
            '<div style="margin:14px 0 4px;padding:8px 10px;background:#eef3f8;border-left:4px solid #1f5a94;font-weight:700">2. Nội dung đề nghị</div>',
        },
        {
          type: 'textfield',
          id: 'Field_ten_nhiem_vu',
          key: 'tenNhiemVu',
          label: 'Tên nhiệm vụ KHCN',
          validate: { required: true },
        },
        {
          type: 'textfield',
          id: 'Field_loai_nhiem_vu',
          key: 'loaiNhiemVu',
          label: 'Loại nhiệm vụ',
          validate: { required: true },
          defaultValue: 'đề tài KHCN',
        },
        {
          type: 'textfield',
          id: 'Field_linh_vuc_hoi_dong',
          key: 'linhVucHoiDong',
          label: 'Hội đồng KHCN/lĩnh vực',
          defaultValue: 'lĩnh vực vũ khí, trang bị công nghệ cao',
        },
        {
          type: 'textarea',
          id: 'Field_can_cu_bo_sung',
          key: 'canCuBoSung',
          label: 'Căn cứ bổ sung (nếu có)',
          description: 'Mỗi căn cứ trên một dòng; nội dung sẽ được đưa vào công văn.',
        },
        {
          type: 'textfield',
          id: 'Field_tai_lieu_dinh_kem',
          key: 'taiLieuDinhKem',
          label: 'Tài liệu đính kèm',
          validate: { required: true },
          defaultValue: 'Dự thảo Tờ trình về việc đề xuất thực hiện đề tài',
        },
        {
          type: 'html',
          id: 'Html_dau_moi',
          content:
            '<div style="margin:14px 0 4px;padding:8px 10px;background:#eef3f8;border-left:4px solid #1f5a94;font-weight:700">3. Đầu mối phối hợp</div>',
        },
        {
          type: 'html',
          id: 'Html_contact_1',
          content: '<div style="margin-top:8px;font-weight:600">Cá nhân đăng ký Chủ nhiệm đề tài</div>',
        },
        { type: 'textfield', id: 'Field_chuNhiem_ho_ten', key: 'chuNhiemHoTen', label: 'Họ tên', validate: { required: true } },
        { type: 'textfield', id: 'Field_chuNhiem_email', key: 'chuNhiemEmail', label: 'Email', validate: { required: true } },
        {
          type: 'textfield',
          id: 'Field_chuNhiem_dien_thoai',
          key: 'chuNhiemDienThoai',
          label: 'Số điện thoại',
          validate: { required: true },
        },
        {
          type: 'html',
          id: 'Html_contact_2',
          content: '<div style="margin-top:8px;font-weight:600">Đầu mối Phòng Tài chính VHT</div>',
        },
        { type: 'textfield', id: 'Field_taiChinh_ho_ten', key: 'taiChinhHoTen', label: 'Họ tên', validate: { required: true } },
        { type: 'textfield', id: 'Field_taiChinh_email', key: 'taiChinhEmail', label: 'Email', validate: { required: true } },
        {
          type: 'textfield',
          id: 'Field_taiChinh_dien_thoai',
          key: 'taiChinhDienThoai',
          label: 'Số điện thoại',
          validate: { required: true },
        },
        {
          type: 'html',
          id: 'Html_contact_3',
          content: '<div style="margin-top:8px;font-weight:600">Đầu mối Trung tâm Mua sắm VHT</div>',
        },
        { type: 'textfield', id: 'Field_muaSam_ho_ten', key: 'muaSamHoTen', label: 'Họ tên', validate: { required: true } },
        { type: 'textfield', id: 'Field_muaSam_email', key: 'muaSamEmail', label: 'Email', validate: { required: true } },
        {
          type: 'textfield',
          id: 'Field_muaSam_dien_thoai',
          key: 'muaSamDienThoai',
          label: 'Số điện thoại',
          validate: { required: true },
        },
        {
          type: 'html',
          id: 'Html_contact_4',
          content: '<div style="margin-top:8px;font-weight:600">Đầu mối Phòng CLKHCN VHT</div>',
        },
        { type: 'textfield', id: 'Field_clkhcn_ho_ten', key: 'clkhcnHoTen', label: 'Họ tên', validate: { required: true } },
        { type: 'textfield', id: 'Field_clkhcn_email', key: 'clkhcnEmail', label: 'Email', validate: { required: true } },
        {
          type: 'textfield',
          id: 'Field_clkhcn_dien_thoai',
          key: 'clkhcnDienThoai',
          label: 'Số điện thoại',
          validate: { required: true },
        },
        {
          type: 'html',
          id: 'Html_contact_5',
          content: '<div style="margin-top:8px;font-weight:600">Đầu mối Phòng Nhân sự VHT</div>',
        },
        { type: 'textfield', id: 'Field_nhanSu_ho_ten', key: 'nhanSuHoTen', label: 'Họ tên', validate: { required: true } },
        { type: 'textfield', id: 'Field_nhanSu_email', key: 'nhanSuEmail', label: 'Email', validate: { required: true } },
        {
          type: 'textfield',
          id: 'Field_nhanSu_dien_thoai',
          key: 'nhanSuDienThoai',
          label: 'Số điện thoại',
          validate: { required: true },
        },
        {
          type: 'html',
          id: 'Html_ky_luu',
          content:
            '<div style="margin:14px 0 4px;padding:8px 10px;background:#eef3f8;border-left:4px solid #1f5a94;font-weight:700">4. Ký và lưu văn bản</div>',
        },
        {
          type: 'textfield',
          id: 'Field_chuc_danh_ky',
          key: 'chucDanhKy',
          label: 'Chức danh người ký',
          validate: { required: true },
          defaultValue: 'TỔNG GIÁM ĐỐC',
        },
        {
          type: 'textfield',
          id: 'Field_nguoi_ky',
          key: 'nguoiKy',
          label: 'Họ tên người ký (nếu cần hiển thị)',
        },
        {
          type: 'textarea',
          id: 'Field_noi_nhan_luu',
          key: 'noiNhanLuu',
          label: 'Nơi nhận/lưu',
          validate: { required: true },
          defaultValue: '- Như trên;\n- Lưu: VT, K1. …07.',
        },
      ],
    },
    {
      type: 'html',
      id: 'Html_van_ban_hoan_chinh',
      conditional: { hide: '=cheDoXemVanBan != true' },
      content:
        '<style>\n  .cv-page{max-width:850px;margin:0 auto;padding:28px 42px 48px;background:#fff;color:#111;font-family:"Times New Roman",Times,serif;font-size:17px;line-height:1.45;box-sizing:border-box}\n  .cv-head{display:grid;grid-template-columns:1fr 1fr;gap:28px;text-align:center;line-height:1.25}\n  .cv-head p,.cv-page p{margin:0 0 8px}.cv-bold{font-weight:700}.cv-upper{text-transform:uppercase}.cv-rule{display:inline-block;border-top:1px solid #111;width:120px;margin-top:3px}\n  .cv-meta{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-top:14px;text-align:center;font-style:italic}.cv-meta>div:first-child{font-style:normal}\n  .cv-subject{margin:20px auto 18px;text-align:center;max-width:680px;font-weight:700}.cv-subject .cv-title{font-size:18px}\n  .cv-recipient{display:grid;grid-template-columns:110px 1fr;margin:12px 0 16px}.cv-recipient-label{text-align:right;padding-right:12px;font-weight:700}.cv-lines{white-space:pre-line}\n  .cv-body{text-align:justify;text-indent:36px}.cv-body.no-indent{text-indent:0}.cv-contact{margin-left:28px;text-indent:-14px}.cv-sign{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:26px}.cv-sign>div:last-child{text-align:center;font-weight:700}.cv-sign-space{height:76px}.cv-value:empty::after{content:"................................";font-weight:400}.cv-basis{white-space:pre-line}\n  @media(max-width:680px){.cv-page{padding:18px 14px;font-size:15px}.cv-head,.cv-meta,.cv-sign{gap:12px}.cv-recipient{grid-template-columns:88px 1fr}}\n</style>\n<article class="cv-page">\n  <header class="cv-head">\n    <div><p class="cv-upper">{{donViCapTren}}</p><p class="cv-upper cv-bold">{{donViBanHanh}}</p><span class="cv-rule"></span></div>\n    <div><p class="cv-upper cv-bold">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</p><p class="cv-bold">Độc lập - Tự do - Hạnh phúc</p><span class="cv-rule"></span></div>\n  </header>\n  <div class="cv-meta">\n    <div>Số: <span class="cv-value">{{soCongVan}}</span>/{{kyHieuCongVan}}</div>\n    <div>{{diaDanh}}, ngày <span class="cv-value">{{ngayVanBan}}</span> tháng <span class="cv-value">{{thangVanBan}}</span> năm {{namKy}}</div>\n  </div>\n  <div class="cv-subject"><div class="cv-title">{{trichYeu}}</div><div>“{{tenNhiemVu}}”</div></div>\n  <div class="cv-recipient"><div class="cv-recipient-label">Kính gửi:</div><div class="cv-lines">{{kinhGui}}</div></div>\n  <p class="cv-body">Trước hết, Tổng Công ty Công nghiệp Công nghệ cao Viettel (TCT VHT) xin gửi lời chào trân trọng tới Ban Tổng Giám đốc Tập đoàn, Hội đồng KHCN {{linhVucHoiDong}} (Hội đồng KHCN) và cảm ơn sự phối hợp, hỗ trợ nhiệt tình cho TCT VHT trong thời gian qua;</p>\n  <p class="cv-body">Căn cứ Quyết định số 9415/QĐ-CNVTQĐ ngày 09/11/2023 về việc ban hành Quy chế Khoa học và công nghệ của Công ty mẹ - Tập đoàn Công nghiệp - Viễn thông Quân đội;</p>\n  <p class="cv-body">Căn cứ Quyết định số 11641/QĐ-CNVTQĐ ngày 24/09/2025 của Chủ tịch Tập đoàn về việc sửa đổi một số điều của Quy chế KHCN của Công ty mẹ - Tập đoàn Công nghiệp - Viễn thông Quân đội ban hành kèm theo Quyết định số 9415/QĐ-CNVTQĐ ngày 09/11/2023;</p>\n  <p class="cv-body">Căn cứ Quyết định số 2891/QĐ-CNVTQĐ ngày 31/12/2025 của Chủ tịch Tập đoàn về việc giao kế hoạch sản xuất kinh doanh, xây dựng đơn vị năm 2026 cho Tổng Giám đốc Tổng Công ty Công nghiệp công nghệ cao Viettel;</p>\n  <p class="cv-body">Căn cứ chức năng và nhiệm vụ của TCT VHT,</p>\n  <p class="cv-body cv-basis">{{canCuBoSung}}</p>\n  <p class="cv-body">TCT VHT kính đề nghị Hội đồng KHCN Tập đoàn thẩm định đề xuất {{loaiNhiemVu}} “<span class="cv-bold">{{tenNhiemVu}}</span>”.</p>\n  <p class="cv-body">Nội dung chi tiết theo {{taiLieuDinhKem}} đính kèm công văn này.</p>\n  <p class="cv-body">Kính đề nghị Cơ quan Quản lý KHCN Tập đoàn xem xét tổ chức họp xét duyệt đề tài cấp Tập đoàn. Đầu mối tiếp nhận thông tin, làm rõ về kỹ thuật và các ngành dọc tại TCT VHT như sau:</p>\n  <p class="cv-contact">- Cá nhân đăng ký Chủ nhiệm đề tài: Đồng chí <span class="cv-bold">{{chuNhiemHoTen}}</span><br>(Email: {{chuNhiemEmail}}; SĐT: {{chuNhiemDienThoai}}).</p>\n  <p class="cv-contact">- Đầu mối Phòng Tài chính VHT: Đồng chí <span class="cv-bold">{{taiChinhHoTen}}</span><br>(Email: {{taiChinhEmail}}; SĐT: {{taiChinhDienThoai}}).</p>\n  <p class="cv-contact">- Đầu mối Trung tâm Mua sắm VHT: Đồng chí <span class="cv-bold">{{muaSamHoTen}}</span><br>(Email: {{muaSamEmail}}; SĐT: {{muaSamDienThoai}}).</p>\n  <p class="cv-contact">- Đầu mối Phòng CLKHCN VHT: Đồng chí <span class="cv-bold">{{clkhcnHoTen}}</span><br>(Email: {{clkhcnEmail}}; SĐT: {{clkhcnDienThoai}}).</p>\n  <p class="cv-contact">- Đầu mối Phòng Nhân sự VHT: Đồng chí <span class="cv-bold">{{nhanSuHoTen}}</span><br>(Email: {{nhanSuEmail}}; SĐT: {{nhanSuDienThoai}}).</p>\n  <p class="cv-body">Một lần nữa, TCT VHT xin cảm ơn và rất mong Cơ quan Quản lý KHCN Tập đoàn hỗ trợ đơn vị triển khai xét duyệt NV KHCN nêu trên.</p>\n  <p class="cv-body no-indent">Trân trọng./.</p>\n  <footer class="cv-sign">\n    <div><p class="cv-bold">Nơi nhận:</p><div class="cv-lines">{{noiNhanLuu}}</div></div>\n    <div><p>{{chucDanhKy}}</p><div class="cv-sign-space"></div><p>{{nguoiKy}}</p></div>\n  </footer>\n</article>',
    },
  ],
}
