package vn.vht.qtkhcn.security;
import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Component; import org.springframework.web.client.*; import vn.vht.qtkhcn.service.TaskActionException;
/** Resolves the current demo user against the central identity-service catalog. */
@Component public class WorkflowDemoIdentityProvider { private final RestClient identity;
 @org.springframework.beans.factory.annotation.Autowired public WorkflowDemoIdentityProvider(@Value("${qtkhcn.identity.base-url:http://127.0.0.1:8095}")String baseUrl,@Value("${qtkhcn.identity.service-token:}")String token){this(RestClient.builder(),baseUrl,token);}
 WorkflowDemoIdentityProvider(RestClient.Builder builder,String baseUrl,String token){identity=builder.baseUrl(baseUrl).defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+token).build();}
 public WorkflowDemoIdentity resolve(String header){String user=validate(header);try{Effective e=identity.get().uri("/internal/users/{id}/effective-permissions",user).retrieve().body(Effective.class);if(e==null)throw forbidden();return new WorkflowDemoIdentity(e.userId(),nullSafe(e.roleCodes()),nullSafe(e.permissions()),e.administrator());}catch(HttpClientErrorException.NotFound e){throw forbidden();}catch(RestClientException e){throw new TaskActionException("IDENTITY_UNAVAILABLE",HttpStatus.SERVICE_UNAVAILABLE,"Identity service is unavailable.");}}
 private static String validate(String value){if(value==null||value.isBlank())throw new TaskActionException("IDENTITY_REQUIRED",HttpStatus.BAD_REQUEST,"X-QTKHCN-User-Id is required.");String x=value.trim().toLowerCase(Locale.ROOT);if(x.length()>128)throw new TaskActionException("IDENTITY_INVALID",HttpStatus.BAD_REQUEST,"X-QTKHCN-User-Id must not exceed 128 characters.");return x;}
 private static TaskActionException forbidden(){return new TaskActionException("IDENTITY_FORBIDDEN",HttpStatus.FORBIDDEN,"Identity is not active or allowed.");} private static Set<String>nullSafe(Set<String>x){return x==null?Set.of():x;}
 private record Effective(String userId,Set<String> roleCodes,Set<String> permissions,boolean administrator){}
}
