package vn.vht.qtkhcn.identity;
import static org.junit.jupiter.api.Assertions.*; import static vn.vht.qtkhcn.identity.web.dto.IdentityDtos.*; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.testcontainers.service.connection.ServiceConnection; import org.testcontainers.junit.jupiter.Container; import org.testcontainers.junit.jupiter.Testcontainers; import org.testcontainers.postgresql.PostgreSQLContainer; import vn.vht.qtkhcn.identity.service.IdentityService;
@Testcontainers @SpringBootTest(properties="qtkhcn.internal.service-token=test-token")
class IdentityServiceIntegrationTest { @Container @ServiceConnection static PostgreSQLContainer db=new PostgreSQLContainer("postgres:16-alpine"); @Autowired IdentityService service;
 @Test void migrationSeedsCatalogAndPreservesLegacyPermissions(){assertEquals(18,service.permissions().size());assertEquals(13,service.features().size());assertEquals(4,service.dataScopes().size());assertTrue(service.roles().size()>=30);EffectivePermissionsResponse e=service.effective("pm@example.com");assertEquals(Set.of("NNC","PA","PM"),e.roleCodes());assertTrue(e.permissions().contains("PROCESS_STEP"));assertTrue(e.featurePermissions().stream().anyMatch(x->x.featureCode().equals("GENERAL")&&x.permissionCodes().contains("PROCESS_STEP")));assertEquals(3,e.assignments().size());assertTrue(e.apps().contains("qlnvkhcn"));}
 @Test void createsUserAssignmentAndRejectsFreeTextScope(){var u=service.createUser(new UserRequest("new.user@example.com","NV001","Người dùng mới","Kỹ sư",null,"ACTIVE",false));var a=service.assign(u.id(),new AssignmentRequest("PM","OWN_MISSION",null,null,null));assertEquals("PM",a.roleCode());assertEquals(Set.of("PM"),service.effective(u.id().toString()).roleCodes());assertThrows(IllegalArgumentException.class,()->service.assign(u.id(),new AssignmentRequest("PM","ARBITRARY",null,null,null)));service.revoke(u.id(),a.id());service.deleteUser(u.id());assertTrue(service.auditLog().stream().anyMatch(x->x.eventType().equals("ROLE_REVOKED")));}
 @Test void replacesUserAppsAndAuditsDelta(){var user=service.users().stream().filter(x->x.email().equals("pm@example.com")).findFirst().orElseThrow();var result=service.replaceUserApps(user.id(),Set.of("qlnvkhcn","quytrinh"));assertEquals(Set.of("qlnvkhcn","quytrinh"),result.appCodes());assertEquals(result.appCodes(),service.effective(user.id().toString()).apps());assertTrue(service.auditLog().stream().anyMatch(x->x.eventType().equals("APP_GRANTED")));}
 @Test void createsRoleWithFeatureMatrix(){var created=service.createRole(new RoleRequest("TEST_MATRIX","Test matrix","BUSINESS",true,null,List.of(new MatrixEntryRequest("DOSSIER",Set.of("VIEW","EDIT"),true))));assertEquals(Set.of("VIEW","EDIT"),created.permissionCodes());assertEquals("DOSSIER",created.matrix().getFirst().featureCode());}
}
