import {
  ApartmentOutline,
  ApiOutline,
  BookOutline,
  CarryOutOutline,
  DashboardOutline,
  DatabaseOutline,
  ExperimentOutline,
  FormOutline,
  HistoryOutline,
  KeyOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PartitionOutline,
  SafetyOutline,
  TeamOutline,
  ThunderboltOutline,
  UserOutline,
} from '@ant-design/icons-angular/icons';

/** Icon dùng trong shell (sider/header) + login — đăng ký tường minh, tránh bundle cả bộ icon. */
export const NAV_ICONS = [
  ApartmentOutline,
  ApiOutline,
  BookOutline,
  CarryOutOutline,
  DashboardOutline,
  DatabaseOutline,
  ExperimentOutline,
  FormOutline,
  HistoryOutline,
  KeyOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PartitionOutline,
  SafetyOutline,
  TeamOutline,
  ThunderboltOutline,
  UserOutline,
];
